o_calcule_observateur.o: o_calcule_observateur.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h
o_cote.o: o_cote.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_vue.h
o_offline.o: o_offline.c /home/etu/p1306459/NE-2.5/./TYPES/t_gl.h \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h
o_test.o: o_test.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_table.h
o_triplet_poids.o: o_triplet_poids.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_xxx.o: o_xxx.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h
o_yyy.o: o_yyy.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_vue.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_etat_courant.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/stl.h
