t_base.o: t_base.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h
t_geometrie.o: t_geometrie.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h t_geometrie.h
t_gl.o: t_gl.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h t_gl.h t_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/s_string.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_xt_interface.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/o_interface.h
t_image.o: t_image.c t_image.h t_gl.h \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h t_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_fichier.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/s_string.h \
 /usr/include/libpng16/png.h /usr/include/libpng16/pnglibconf.h \
 /usr/include/libpng16/pngconf.h
t_prog.o: t_prog.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h
t_variable.o: t_variable.c \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_xt_interface.h \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/o_interface.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_fichier.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/s_string.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_etat_courant.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_modele.h
t_widget.o: t_widget.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_xt_interface.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/o_interface.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_repartiteur.h t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_fichier.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/s_string.h
