figure.o: figure.c /home/etu/p1306459/NE-2.5/M2IMG/../COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../TYPES/t_geometrie.h
o_bezier.o: o_bezier.c /home/etu/p1306459/NE-2.5/M2IMG/../COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../TYPES/t_geometrie.h
o_nurbs.o: o_nurbs.c /home/etu/p1306459/NE-2.5/M2IMG/../COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/M2IMG/../TYPES/t_geometrie.h
