o_affiche_octree.o: o_affiche_octree.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h
o_ajoute_pt.o: o_ajoute_pt.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_arbre.o: o_arbre.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_vue.h
o_bezier.o: o_bezier.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_bresenham.o: o_bresenham.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_convexe.o: o_convexe.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_decoupage.o: o_decoupage.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h
o_ex_arbre.o: o_ex_arbre.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_vue.h
o_ex_bresenham.o: o_ex_bresenham.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_ex_decoupage.o: o_ex_decoupage.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h
o_ex_plan.o: o_ex_plan.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_vue.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_etat_courant.h
o_ex_rotation.o: o_ex_rotation.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/s_string.h
o_ex_translation.o: o_ex_translation.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/s_string.h
o_gpao_piece.o: o_gpao_piece.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h
o_gpao_reserve.o: o_gpao_reserve.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/s_string.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_gpao_transporteur.o: o_gpao_transporteur.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h
o_inter_bez_seg.o: o_inter_bez_seg.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_inter_octree.o: o_inter_octree.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h
o_interseg.o: o_interseg.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_iso_surf.o: o_iso_surf.c /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_graphique.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_etat_courant.h
o_primitives.o: o_primitives.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./OBJETS/u_etat_courant.h
o_triangulation.o: o_triangulation.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h
o_x_rotation.o: o_x_rotation.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/s_string.h
o_x_translation.o: o_x_translation.c \
 /home/etu/p1306459/NE-2.5/./COEUR/o_objet.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/eprintf.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec_base.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/codec.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/l_liste.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_memoire.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_widget.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/u_etat.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_base.h \
 /home/etu/p1306459/NE-2.5/./TYPES/t_geometrie.h \
 /home/etu/p1306459/NE-2.5/./UTILITAIRES/s_string.h
